/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lance
 */
public class EditStopWordListJPanel extends javax.swing.JPanel 
{
    private MainFrame parentMainFrame;
    private DefaultTableModel model;
    private Vector vectorColName;//JTable 的抬头
    private Vector tableContent;
    
    
    /**
     * Creates new form EditStopWordListJPanel
     */
    public EditStopWordListJPanel(MainFrame mainFrame) 
    {
        parentMainFrame = mainFrame;
        initComponents();
        //send running status to main frame
        parentMainFrame.insertTextPane("EditStopWordListJPanel initiated!\r\n",Color.BLUE);
        
        //创建表头
        vectorColName = new Vector();
        vectorColName.addElement("id");
        vectorColName.addElement("stopword");
        //创建table model
        model = new DefaultTableModel();
  
        Vector vectorRow1 = new Vector();
        vectorRow1.addElement(new String("1"));
        vectorRow1.addElement(new String("a"));
        
        Vector vectorRow2 = new Vector();
        vectorRow2.addElement(new String("2"));
        vectorRow2.addElement(new String("b"));
        
        Vector vectorData = new Vector();
        vectorData.addElement(vectorRow1);
        vectorData.addElement(vectorRow2);
        
        model.setDataVector(vectorData,vectorColName);
        this.stopWordJTable.setModel(model);
        vectorRow1.clear();
        vectorRow1.addElement(new String("11"));
        vectorRow1.addElement(new String("aa"));
        vectorData.clear();
        vectorData.addElement(vectorRow1);
        vectorData.addElement(vectorRow2);
        model.setDataVector(vectorData,vectorColName);
        this.stopWordJTable.setModel(model);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stopWordJTable = new javax.swing.JTable();
        LoadStopWordJButton = new javax.swing.JButton();
        OverwriteStopWordJButton = new javax.swing.JButton();
        InsertStopWordJButton = new javax.swing.JButton();

        jLabel1.setText("EditStopWordListJPanel");

        stopWordJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Stop Word"
            }
        ));
        jScrollPane1.setViewportView(stopWordJTable);

        LoadStopWordJButton.setText("Load");

        OverwriteStopWordJButton.setText("Overwrite");
        OverwriteStopWordJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OverwriteStopWordJButtonActionPerformed(evt);
            }
        });

        InsertStopWordJButton.setText("Insert");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OverwriteStopWordJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LoadStopWordJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InsertStopWordJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(LoadStopWordJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OverwriteStopWordJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InsertStopWordJButton)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OverwriteStopWordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OverwriteStopWordJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OverwriteStopWordJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertStopWordJButton;
    private javax.swing.JButton LoadStopWordJButton;
    private javax.swing.JButton OverwriteStopWordJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stopWordJTable;
    // End of variables declaration//GEN-END:variables
}
