/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author lance
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() 
    {
        initComponents();
        insertTextPane("Welcome to use this DB interface. Let me know if you have any suggestions: ysong8@ncsu.edu.\r\n",Color.BLACK);
        //Download Original Profiles Panel
        //DownloadOriginalProfilesJPanel downloadOriginalProfilesJPanel = new DownloadOriginalProfilesJPanel(this);
        //downloadOriginalProfilesJPanel.setName("Download Original Profiles");
        //this.MainFrameTabbedPane.add(downloadOriginalProfilesJPanel); 
        //edit stop word list Panel
        //EditStopWordListJPanel editStopWordListJPanel = new EditStopWordListJPanel(this);
        //editStopWordListJPanel.setName("Edit Stop World List");
        //this.MainFrameTabbedPane.add(editStopWordListJPanel); 
        //Data querry Panel
        ContentSearchJPanel contentSearchJPanel = new ContentSearchJPanel(this);
        contentSearchJPanel.setName("Content Querry");
        this.MainFrameTabbedPane.add(contentSearchJPanel); 
        //DB Dump Panel
        DumpExtracted2DBJPanel dumpExtracted2DBJPanel = new DumpExtracted2DBJPanel(this);
        dumpExtracted2DBJPanel.setName("Dump Paragraph 2 DB");
        this.MainFrameTabbedPane.add(dumpExtracted2DBJPanel); 
        //Profile Generation Panel
        GenerateProfileJPanel generateProfileJPanel = new GenerateProfileJPanel(this);
        generateProfileJPanel.setName("Generate Profile");
        this.MainFrameTabbedPane.add(generateProfileJPanel); 
    }
    //根据传入的颜色及文字，将文字插入文本域 
     public void insertTextPane(String text, Color textColor)
    {
        SimpleAttributeSet set = new SimpleAttributeSet();
        StyleConstants.setForeground(set, textColor);//设置文字颜色 
        StyleConstants.setFontSize(set, 12);//设置字体大小 
        Document doc = this.RunningStatusTextPane.getStyledDocument();
        try 
        {
            doc.insertString(doc.getLength(), text, set);//插入文字 
        } 
        catch (BadLocationException e) 
        {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFrameTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        RunningStatusTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(RunningStatusTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addComponent(MainFrameTabbedPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainFrameTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainFrameTabbedPane;
    private javax.swing.JTextPane RunningStatusTextPane;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
